name: Deploy

on:
    push:

jobs:
    cleanFiles:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  script: |
                      if [ -d "/home/blury/perso/discord/discord-bot-ncls" ]; then
                        rm -rf /home/blury/perso/discord/discord-bot-ncls
                      fi

    uploadFiles:
        runs-on: ubuntu-latest
        needs: cleanFiles
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Copy repository contents via scp
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  source: "."
                  target: "/home/blury/perso/discord/discord-bot-ncls"

    buildAndRun:
        needs: uploadFiles
        runs-on: ubuntu-latest
        env:
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            DISCORD_BOT_CREATOR: ${{ secrets.DISCORD_BOT_CREATOR }}
            DISCORD_BOT_PREFIX: ${{ secrets.DISCORD_BOT_PREFIX }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  envs: DISCORD_BOT_TOKEN,UPTIME_ROBOT_API_KEY
                  script: |
                      cd /home/blury/perso/discord/discord-bot-ncls
                      touch .env
                      echo "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}" >> .env
                      echo "DISCORD_BOT_CREATOR=${DISCORD_BOT_CREATOR}" >> .env
                      echo "DISCORD_BOT_PREFIX=${DISCORD_BOT_PREFIX}" >> .env
                      echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env

                      docker compose down --remove-orphans
                      docker compose up -d
